Repository OZ-Coding-School/oz_externship_fe_02_team1, pull requests merged in 2025-09, with the labels that each got.

#26 Feature: 공용 Text 컴포넌트 추가
  src/components/common/index.ts
  src/components/common/text/H1.tsx
  src/components/common/text/H2.tsx
  src/components/common/text/H3.tsx
  src/components/common/text/H4.tsx
  src/components/common/text/H5.tsx
  src/components/common/text/Text.tsx
  src/components/common/text/index.ts
Labels: enhancement

#17 Feature: 상태변화를 프롭스로 관리하는 공통 Input컴포넌트 textarea 제작
  package-lock.json
  package.json
  src/components/common/form/DateInput.tsx
  src/components/common/form/Index.ts
  src/components/common/form/Input.tsx
  src/components/common/form/Textarea.tsx
  src/components/common/form/TimeInput.tsx
  src/components/common/form/form.styles.ts
  src/components/common/form/form.type.ts
  src/components/index.ts
Labels: enhancement

#29 Feature: 모달 베이스/프리셋 제작
  src/components/common/index.ts
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/ModalBody.tsx
  src/components/common/modal/ModalFooter.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/common/modal/ModalPresets.tsx
  src/components/common/modal/index.ts
  src/components/common/modal/modal.types.ts
  src/components/common/modal/modal.utils.ts
  src/components/common/modal/modalSizes.ts
Labels: enhancement

#28 Feature: 공통 이미지 카드 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/card/Card.tsx
  src/components/common/card/index.ts
  src/components/common/index.ts
  src/main.tsx
Labels: enhancement

#31 Refactor: common index에 badge export추가
  src/components/common/index.ts
Labels: documentation

#35 Fix: ESLint import resolver 설정 추가로 @/* alias 인식 오류 해결
  eslint.config.js
  package-lock.json
  package.json
Labels: bug

#27 Feature: 공통 Avatar 컴포넌트 구현
  src/components/common/avatar/Avatar.tsx
  src/components/common/avatar/AvatarInitials.tsx
  src/components/common/avatar/AvatarStatusDot.tsx
  src/components/common/avatar/avatar.constants.ts
  src/components/common/avatar/avatar.types.ts
  src/components/common/avatar/index.ts
  src/components/common/index.ts
Labels: enhancement

#44 Fix: BaseModal 훅 호출 순서 수정 ESlint오류 해결
  src/components/common/modal/BaseModal.tsx
Labels: bug

#52 Refactor: alias 경로 추가 및 import 경로 업데이트
  src/assets/icons/index.ts
  src/assets/index.ts
  src/components/common/avatar/Avatar.tsx
  src/components/common/avatar/AvatarInitials.tsx
  src/components/common/avatar/AvatarStatusDot.tsx
  src/components/common/avatar/index.ts
  src/components/common/badge/index.ts
  src/components/common/button/Button.tsx
  src/components/common/button/index.ts
  src/components/common/card/Card.tsx
  src/components/common/card/index.ts
  src/components/common/form/DateInput.tsx
  src/components/common/form/Index.ts
  src/components/common/form/Input.tsx
  src/components/common/form/Textarea.tsx
  src/components/common/form/TimeInput.tsx
  src/components/common/form/form.styles.ts
  src/components/common/image-upload/ImageUpload.tsx
  src/components/common/image-upload/index.ts
  src/components/common/index.ts
  src/components/common/markdown-editor/MarkdownEditor.tsx
  src/components/common/markdown-editor/MarkdownEditorHint.tsx
  src/components/common/markdown-editor/MarkdownPreview.tsx
  src/components/common/markdown-editor/index.ts
  src/components/common/markdown-editor/markdownEditor.constants.ts
  src/components/common/markdown-editor/markdownEditor.utils.ts
  src/components/common/modal/BaseModal.tsx
  src/components/common/modal/ModalBody.tsx
  src/components/common/modal/ModalFooter.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/common/modal/ModalPresets.tsx
  src/components/common/modal/index.ts
  src/components/common/modal/modal.types.ts
  src/components/common/rating/Rating.tsx
  src/components/common/rating/index.ts
  src/components/common/rating/rating.interactions.ts
  src/components/common/text/H1.tsx
  src/components/common/text/H2.tsx
  src/components/common/text/H3.tsx
  src/components/common/text/H4.tsx
  src/components/common/text/H5.tsx
  src/components/common/text/Text.tsx
  src/components/common/text/index.ts
  src/components/common/toast/Toast.tsx
  src/components/common/toast/index.ts
  src/components/index.ts
  src/utils/index.ts
  tsconfig.app.json
  vite.config.ts
Labels: refactor

#55 Fix: TypeScript 경로와 Vite alias 수정하여 import 오류 해결
  tsconfig.app.json
  vite.config.ts
Labels: bug

#56 Feature: breadcrumb 컴포넌트 제작
  src/components/common/bread-crumb/BreadCrumb.tsx
  src/components/common/bread-crumb/index.ts
Labels: enhancement

#58 Feature: 로딩 스켈레톤 컴포넌트 제작
  src/components/common/index.ts
  src/components/common/skeleton/Skeleton.tsx
  src/components/common/skeleton/SkeletonAvatar.tsx
  src/components/common/skeleton/SkeletonCard.tsx
  src/components/common/skeleton/SkeletonText.tsx
  src/components/common/skeleton/index.ts
Labels: enhancement

#63 Feature: 기본 카드 컴포넌트
  src/components/common/card/Card.tsx
  src/components/common/image-card/ImageCard.tsx
  src/components/common/image-card/index.ts
  src/components/common/index.ts
Labels: enhancement

#74 Feature: Header 사용자 메뉴 추가 및 스타일 수정
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderSideMenu.tsx
  src/components/layout/header/UserDropdown.tsx
  src/components/layout/header/UserMenu.tsx
  src/components/layout/header/UserMenuButton.tsx
  src/components/layout/header/UserProfileMenu.tsx
  src/components/layout/header/index.ts
  src/components/layout/layout/Layout.tsx
Labels: enhancement

#64 Feature: 그룹만들기 페이지 제작 컴포넌트
  package-lock.json
  package.json
  src/components/common/date-picker/index.ts
  src/components/common/form/DateInput.tsx
  src/components/common/form/index.ts
  src/components/common/index.ts
  src/components/create-group/BasicInfoSection.tsx
  src/components/create-group/DatePickerModal.tsx
  src/components/create-group/DateRangeFields.tsx
  src/components/create-group/LecturePickerSection.tsx
  src/components/create-group/MembersSlider.styles.ts
  src/components/create-group/MembersSlider.tsx
  src/components/create-group/PeriodMembersSection.tsx
  src/components/create-group/constants.ts
  src/components/create-group/data.ts
  src/components/create-group/index.ts
  src/components/create-group/types.ts
  src/components/create-group/useCreateGroupForm.ts
  src/components/index.ts
  src/hooks/useDateModal.ts
  src/pages/CreateGroup.tsx
Labels: enhancement

#77 Style: header 배경색 및 z-index 지정
  src/components/layout/header/Header.tsx
Labels: style

#87 Feature: 캘린더 컴포넌트 제작
  src/assets/icons/chevron.tsx
  src/components/common/date-picker/Calendar.tsx
  src/components/common/date-picker/calendar.classnames.ts
  src/components/common/date-picker/calendar.constants.ts
  src/components/common/date-picker/calendar.types.ts
  src/components/common/date-picker/calendar.utils.ts
  src/components/common/date-picker/index.ts
  src/components/common/form/DateInput.tsx
  src/components/create-group/DatePickerModal.tsx
  src/components/create-group/index.ts
  src/pages/CreateGroup.tsx
Labels: enhancement

#84 Feature: 스터디 기록 수정 페이지 파일 업로드 컴포넌트
  package-lock.json
  package.json
  src/components/common/toast/Toast.tsx
  src/components/index.ts
  src/components/study-log/FileUpload.tsx
  src/components/study-log/UploadPlaceholder.tsx
  src/components/study-log/UploadedFileList.tsx
  src/components/study-log/fileUpload.utils.ts
  src/components/study-log/index.ts
  src/constants/fileUpload.ts
  src/constants/index.ts
Labels: enhancement

#113 Feature: 스터디그룹 상세 페이지 반응형 디자인 적용 및 헤더 nav 기능 추가
  package-lock.json
  package.json
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/HeaderNav.tsx
  src/components/study-group-detail/StudyGroupLecture.tsx
  src/constants/navList.ts
  src/pages/StudyGroupDetail.tsx
Labels: enhancement

#110 Feature: 스케줄 캘린더 컴포넌트 및 스케줄 관리 섹션 추가
  src/components/common/date-picker/Calendar.tsx
  src/components/common/date-picker/calendar.utils.ts
  src/components/study-group-detail/StudyGroupSchedule.tsx
  src/components/study-group-detail/calendar/CalendarBody.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/calendar/CalendarDays.tsx
  src/components/study-group-detail/calendar/CalendarHeader.tsx
  src/components/study-group-detail/calendar/ScheduleCalendar.tsx
  src/components/study-group-detail/calendar/index.ts
  src/components/study-group-detail/index.ts
  src/mocks/studyGroupDetail.ts
  src/pages/StudyGroupDetail.tsx
  src/types/studyGroup.ts
  src/utils/formatters.ts
Labels: enhancement

#116 Fix: 이미지 카드 컴포넌트 이미지 비율 수정
  src/components/common/image-card/ImageCard.tsx
  src/pages/StudyGroupDetail.tsx
Labels: style

#131 Feature: 스터디그룹 수정 페이지 컴포넌트 추가 및 라우트 설정
  src/App.tsx
  src/components/common/image-card/ImageCard.tsx
  src/components/layout/header/HeaderNav.tsx
  src/components/layout/layout/Layout.tsx
  src/components/study-log/FileUpload.tsx
  src/components/study-log/fileUpload.utils.ts
  src/pages/StudyGroupEdit.tsx
  src/pages/index.ts
Labels: enhancement

#132 Feature: 스터디 그룹 수정 페이지 내 기본 정보 입력 섹션 추가
  src/components/common/form/Input.tsx
  src/components/common/image-upload/ImageUpload.tsx
  src/components/common/image-upload/index.ts
  src/components/create-study-group/PrimaryInfoSection.tsx
  src/components/create-study-group/index.ts
  src/components/index.ts
  src/pages/StudyGroupEdit.tsx
Labels: enhancement

#125 Feature: 스터디 기록 작성 페이지 UI
  src/App.tsx
  src/components/common/bread-crumb/BreadCrumb.tsx
  src/components/common/bread-crumb/index.ts
  src/components/common/index.ts
  src/components/create-study-log/CreateStudyLog.tsx
  src/components/create-study-log/FileUpload.tsx
  src/components/create-study-log/UploadPlaceholder.tsx
  src/components/create-study-log/UploadedFileList.tsx
  src/components/create-study-log/fileUpload.utils.ts
  src/components/create-study-log/index.ts
  src/components/index.ts
  src/components/study-log/index.ts
  src/constants/breadCrumbPath.ts
  src/constants/index.ts
  src/pages/CreateStudyLog.tsx
  src/pages/index.ts
Labels: enhancement

#135 Feature: 스터디 그룹 수정 페이지 내 강의 선택 섹션 추가
  src/components/create-study-group/LectureSelectSection.tsx
  src/components/create-study-group/SelectedLectureCard.tsx
  src/components/create-study-group/index.ts
  src/pages/StudyGroupEdit.tsx
Labels: enhancement

#136 Feature: 스터디그룹 수정 페이지 UI/UX 개선 및 기능 구현
  src/components/create-study-group/LectureSelectSection.tsx
  src/components/create-study-group/PeriodMemberSection.tsx
  src/components/create-study-group/PrimaryInfoSection.tsx
  src/components/study-group-detail/StudyGroupHeader.tsx
  src/components/study-log-detail/LogDetailHeader.tsx
  src/hooks/index.ts
  src/hooks/usePageNav.ts
  src/pages/StudyGroupEdit.tsx
  tsconfig.app.json
Labels: enhancement

#148 Feature: 스케줄 상세 조회 모달 추가
  src/components/common/modal/ModalPresets.tsx
  src/components/common/modal/index.ts
  src/components/common/modal/modal.types.ts
  src/components/create-study-group/modal/DatePickerModal.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDatePickerModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailDiv.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/components/study-group-detail/modal/index.ts
  src/mocks/studyGroupDetail.ts
  src/types/studyGroup.ts
Labels: enhancement

#146 Feature: 스터디 기록 상세페이지 메인 부분
  package-lock.json
  package.json
  src/assets/icons/attachment.svg
  src/assets/icons/download.svg
  src/assets/icons/index.ts
  src/assets/icons/pdf.svg
  src/assets/icons/zip.svg
  src/components/common/markdown-editor/MarkdownPreview.tsx
  src/components/common/markdown-editor/index.ts
  src/components/common/markdown-editor/markdown-editor.css
  src/components/study-log-detail/AISummary.tsx
  src/components/study-log-detail/LogDetailAISummary.tsx
  src/components/study-log-detail/LogDetailAttachments.tsx
  src/components/study-log-detail/LogDetailHeader.tsx
  src/components/study-log-detail/LogDetailMain.tsx
  src/components/study-log-detail/index.ts
  src/mocks/dummyStudyLog.ts
  src/pages/StudyLogDetail.tsx
  src/types/index.ts
  src/types/studyLog.ts
Labels: enhancement

#166 Feature: 리뷰 작성 모달 ui 추가
  src/components/common/modal/ModalPresets.tsx
  src/components/common/rating/Rating.tsx
  src/components/study-group/index.ts
  src/components/study-group/modal/ReviewWriteModal.tsx
  src/components/study-group/modal/index.ts
  src/mocks/studyGroupDetail.ts
  src/types/studyGroup.ts
Labels: enhancement

#167 Refactor: 스터디 기록 생성 페이지 리팩토링
  src/App.tsx
  src/components/create-study-log/CreateStudyLog.tsx
  src/components/create-study-log/CreateStudyLogFooter.tsx
  src/components/create-study-log/CreateStudyLogHeader.tsx
  src/components/create-study-log/CreateStudyLogMarkdown.tsx
  src/components/create-study-log/CreateStudyLogTitle.tsx
  src/components/create-study-log/LogFileUpload.tsx
  src/components/create-study-log/LogUploadPlaceholder.tsx
  src/components/create-study-log/LogUploadedFileList.tsx
  src/components/create-study-log/index.ts
  src/components/create-study-log/logFileUpload.utils.ts
  src/pages/CreateStudyLog.tsx
Labels: refactor

#173 Feature: 채팅 아이콘 추가
  src/components/common/chat/ChatAlertCount.tsx
  src/components/common/chat/ChatIcon.tsx
  src/components/common/chat/index.ts
  src/components/common/index.ts
  src/components/create-study-log/LogFileUpload.tsx
  src/components/layout/layout/Layout.tsx
  src/pages/CreateStudyLog.tsx
Labels: enhancement

#172 Feature: 공용으로 사용가능한 섹션 헤더입니다.
  src/components/common/index.ts
  src/components/common/section-header/SectionHeader.tsx
  src/components/common/section-header/index.ts
  src/components/create-study-log/CreateStudyLogHeader.tsx
Labels: enhancement

#178 Feature: api 명세 기반 인터페이스 작성
  src/components/create-study-group/form-parts/LectureSelectSection.tsx
  src/components/create-study-group/form-parts/SelectedLectureCard.tsx
  src/components/create-study-group/form/Form.types.ts
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/create-study-group/form/StudyGroupFormContainer.tsx
  src/components/study-group-detail/StudyGroupHeader.tsx
  src/components/study-group-detail/StudyGroupInfo.tsx
  src/components/study-group-detail/StudyGroupLecture.tsx
  src/components/study-group-detail/StudyGroupLogList.tsx
  src/components/study-group-detail/StudyGroupMember.tsx
  src/components/study-group-detail/StudyGroupSchedule.tsx
  src/components/study-group-detail/calendar/CalendarBody.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/calendar/ScheduleCalendar.tsx
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/EditScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/components/study-group-detail/modal/ScheduleForm.tsx
  src/components/study-group/modal/ReviewListModal.tsx
  src/components/study-group/modal/ReviewWriteModal.tsx
  src/components/study-log-detail/LogDetailAttachments.tsx
  src/components/study-log-detail/LogDetailHeader.tsx
  src/components/study-log-detail/LogDetailMain.tsx
  src/mocks/dummyStudyLog.ts
  src/mocks/studyGroupDetail.ts
  src/pages/StudyGroupDetail.tsx
  src/pages/StudyLogDetail.tsx
  src/types/chat.ts
  src/types/index.ts
  src/types/lecture.ts
  src/types/review.ts
  src/types/schedule.ts
  src/types/studyGroup.ts
  src/types/studyLog.ts
  src/types/user.ts
  src/utils/review.ts
Labels: enhancement

#184 Feature: axios 인스턴스 생성 및 api 경로 상수 파일 생성
  src/constants/apiPath.ts
  src/lib/fetcher.ts
Labels: enhancement

#194 Fix: 스터디 그룹 폼 일부 컴포넌트 동작 오류
  src/components/create-study-group/form-parts/PeriodMemberSection.tsx
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/utils/date.ts
  src/utils/formatters.ts
Labels: bug

#198 Feature: msw 설치 및 스터디 그룹 생성 api 연동 (msw)
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/api.ts
  src/api/index.ts
  src/api/studyGroupApi.ts
  src/components/common/chat/ChatIcon.tsx
  src/components/common/chat/ChatMemberList.tsx
  src/components/common/chat/ChatRoom.tsx
  src/components/common/chat/ChatRoomList.tsx
  src/components/create-study-group/form-parts/PrimaryInfoSection.tsx
  src/components/create-study-group/form/Form.types.ts
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/create-study-group/form/StudyGroupFormContainer.tsx
  src/components/study-group-detail/modal/ScheduleForm.tsx
  src/components/study-group/StudyGroupCard.tsx
  src/components/study-group/modal/ReviewListModal.tsx
  src/components/study-group/modal/ReviewWriteModal.tsx
  src/constants/apiPath.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useStudyGroupQueries.ts
  src/lib/fetcher.ts
  src/lib/index.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/datas/chatListMocks.ts
  src/mocks/datas/chatRoomMocks.ts
  src/mocks/datas/dummyStudyLog.ts
  src/mocks/datas/studyGroupDetail.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/studyGroupHandlers.ts
  src/pages/StudyGroup.tsx
  src/pages/StudyGroupDetail.tsx
  src/pages/StudyLogDetail.tsx
  src/types/api-request-types/index.ts
  src/types/api-request-types/studyGroup-request-types.ts
  src/types/api-response-types/index.ts
  src/types/api-response-types/studyGroup-response-types.ts
  src/types/index.ts
  src/types/studyGroup.ts
  tsconfig.app.json
Labels: enhancement

#200 Feature: vercel 배포 설정 파일 추가 및 테스트 랜딩 페이지 추가
  src/App.tsx
  src/hooks/usePageNav.ts
  src/pages/TestLanding.tsx
  src/pages/index.ts
  vercel.json
Labels: enhancement

#205 Refactor: 스터디 그룹 API 및 폼 처리 개선
  src/api/auth.ts
  src/api/group.ts
  src/api/index.ts
  src/api/studyGroupApi.ts
  src/api/types/auth.ts
  src/api/types/group.ts
  src/api/types/index.ts
  src/components/create-study-group/form/StudyGroupFormContainer.tsx
  src/constants/apiPath.ts
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useStudyGroupMutations.ts
  src/hooks/queries/useStudyGroupQueries.ts
  src/lib/fetcher.ts
  src/pages/TestLanding.tsx
  src/types/api-request-types/index.ts
  src/types/api-response-types/index.ts
  src/types/api-response-types/studyGroup-response-types.ts
  src/types/index.ts
  src/utils/form/index.ts
  src/utils/form/studyGroupForm.ts
  src/utils/index.ts
Labels: refactor

#211 Feature: 로그아웃 api 연동 및 사용자 전역 상태 생성
  src/api/auth.ts
  src/components/layout/header/AuthButtonGroup.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderDesktop.tsx
  src/components/layout/header/HeaderMobile.tsx
  src/components/layout/header/UserDropdown.tsx
  src/components/layout/header/side-menu/SideMenu.tsx
  src/components/layout/header/side-menu/SideMenuFooter.tsx
  src/components/layout/layout/Layout.tsx
  src/hooks/index.ts
  src/hooks/useAuthActions.ts
  src/pages/TestLanding.tsx
  src/store/authStore.ts
  src/store/index.ts
  tsconfig.app.json
Labels: enhancement

#223 Feature: 스케줄 추가 api 연동
  src/api/index.ts
  src/api/schedule.ts
  src/api/types/index.ts
  src/api/types/schedule.ts
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/study-group-detail/StudyGroupSchedule.tsx
  src/components/study-group-detail/calendar/CalendarBody.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/calendar/ScheduleCalendar.tsx
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/EditScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/components/study-group-detail/modal/ScheduleForm.tsx
  src/constants/apiPath.ts
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useScheduleMutations.ts
  src/mocks/datas/studyGroupDetail.ts
  src/mocks/datas/studygroupList.ts
  src/types/schedule.ts
  src/types/studyGroup.ts
Labels: enhancement

#222 Feature: 스터디 로그 파일업로드 & 기록 생성 api 호출(MSW)
  src/api/index.ts
  src/api/log.ts
  src/api/types/index.ts
  src/api/types/log.ts
  src/components/create-study-log/LogFileUpload.tsx
  src/components/create-study-log/LogUploadPlaceholder.tsx
  src/components/create-study-log/LogUploadedFileList.tsx
  src/components/create-study-log/index.ts
  src/components/create-study-log/logFileUpload.utils.ts
  src/components/study-log/StudyLogFooter.tsx
  src/components/study-log/StudyLogMarkdown.tsx
  src/components/study-log/StudyLogTitle.tsx
  src/hooks/index.ts
  src/hooks/useLogFileUpload.ts
  src/hooks/usePageNav.ts
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/studyLogHandlers.ts
  src/pages/CreateStudyLog.tsx
  src/pages/EditStudyLog.tsx
  src/utils/form/studyLogForm.ts
Labels: enhancement

#225 Feature: 스케줄 목록 조회 api 연동
  src/api/schedule.ts
  src/api/types/schedule.ts
  src/components/common/chat/ChatRoomList.tsx
  src/components/study-group-detail/StudyGroupSchedule.tsx
  src/components/study-group-detail/calendar/CalendarBody.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/EditScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/constants/apiPath.ts
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useChatRoomsListQuery.ts
  src/hooks/queries/useScheduleListQuery.ts
  src/hooks/queries/useScheduleMutations.ts
  src/hooks/queries/useStudyGroupQuery.ts
  src/lib/fetcher.ts
  src/mocks/datas/studyGroupDetail.ts
  src/pages/StudyGroupDetail.tsx
  src/utils/caseConverter.ts
  src/utils/index.ts
Labels: enhancement

#226 Feature: 스터디 기록 상세조회,수정 api 호출 로직 및 ai생성 리펙토링(MSW)
  src/api/log.ts
  src/api/types/log.ts
  src/assets/icons/image.svg
  src/assets/icons/index.ts
  src/components/create-study-log/LogFileUpload.tsx
  src/components/create-study-log/LogUploadedFileList.tsx
  src/components/create-study-log/index.ts
  src/components/study-log-detail/LogDetailAISummary.tsx
  src/components/study-log-detail/LogDetailAttachments.tsx
  src/components/study-log-detail/LogDetailMain.tsx
  src/components/study-log/StudyLogFooter.tsx
  src/components/study-log/StudyLogMarkdown.tsx
  src/constants/fileUpload.ts
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useStudyLogQuery.ts
  src/hooks/useLogFileUpload.ts
  src/hooks/usePageNav.ts
  src/mocks/datas/dummyStudyLog.ts
  src/mocks/handlers/studyLogHandlers.ts
  src/pages/CreateStudyLog.tsx
  src/pages/EditStudyLog.tsx
  src/pages/StudyLogDetail.tsx
  src/types/studyLog.ts
  src/utils/caseConverter.ts
  src/utils/fileUtils.ts
  src/utils/form/studyLogForm.ts
  src/utils/index.ts
Labels: enhancement

#228 Feature: 스케줄 상세 조회 api 연동
  src/api/schedule.ts
  src/api/types/schedule.ts
  src/components/create-study-group/form/StudyGroupFormContainer.tsx
  src/components/study-group-detail/StudyGroupSchedule.tsx
  src/components/study-group-detail/calendar/CalendarBodyDate.tsx
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/EditScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useScheduleDetailQuery.ts
  src/pages/TestLanding.tsx
Labels: enhancement

#237 Feature: 스터디 로그 수정 api (MSW)
  src/api/log.ts
  src/api/types/log.ts
  src/components/create-study-log/LogFileUpload.tsx
  src/components/study-log/StudyLogFooter.tsx
  src/components/study-log/StudyLogFormContainer.tsx
  src/components/study-log/StudyLogMarkdown.tsx
  src/components/study-log/index.ts
  src/constants/apiPath.ts
  src/hooks/index.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useStudyLogMutations.ts
  src/hooks/queries/useStudyLogQuery.ts
  src/hooks/useLogFileUpload.ts
  src/hooks/usePageNav.ts
  src/hooks/useStudyLogForm.ts
  src/mocks/handlers/studyLogHandlers.ts
  src/pages/CreateStudyLog.tsx
  src/pages/EditStudyLog.tsx
  src/pages/StudyLogDetail.tsx
  src/utils/form/studyLogForm.ts
  src/utils/index.ts
  src/utils/logUtils.ts
Labels: enhancement

#233 Feature: 스터디 기록 목록 조회 api 연동 및 ui 개선
  src/api/log.ts
  src/api/types/log.ts
  src/components/study-group-detail/StudyGroupLogList.tsx
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useLogDetailQuery.ts
  src/hooks/queries/useLogListQuery.ts
  src/hooks/useStudyLogForm.ts
  src/pages/StudyGroupDetail.tsx
  src/pages/StudyLogDetail.tsx
Labels: enhancement

#242 Feature: 멤버 추방 api 연동 (msw)
  src/components/study-group-detail/StudyGroupMember.tsx
  src/constants/apiPath.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useKickMemberMutation.ts
  src/mocks/handlers/studyGroupHandlers.ts
  src/pages/StudyGroupDetail.tsx
Labels: enhancement

#257 Feature: 강의 선택 모달 ui 제작
  src/components/common/form/Checkbox.tsx
  src/components/common/form/index.ts
  src/components/common/index.ts
  src/components/common/modal/ModalPresets.tsx
  src/components/common/pagination/Pagination.tsx
  src/components/common/pagination/index.ts
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/create-study-group/modal/LectureSelectItem.tsx
  src/components/create-study-group/modal/LectureSelectModal.tsx
  src/components/create-study-group/modal/index.ts
  src/mocks/datas/lectureData.ts
  src/types/lecture.ts
Labels: enhancement

#258 Style: 로그 디테일 페이지 반응형 디자인 수정
  src/api/types/auth.ts
  src/components/study-log-detail/LogDetailAISummary.tsx
  src/components/study-log-detail/LogDetailAttachments.tsx
  src/components/study-log-detail/LogDetailHeader.tsx
  src/components/study-log-detail/LogDetailMain.tsx
  src/components/study-log/StudyLogLayout.tsx
  src/hooks/useAuthActions.ts
Labels: style

#259 Feature: 강의 목록 조회 api 연동
  src/api/index.ts
  src/api/lecture.ts
  src/api/types/index.ts
  src/api/types/lecture.ts
  src/components/common/modal/ModalPresets.tsx
  src/components/create-study-group/form-parts/LectureSelectSection.tsx
  src/components/create-study-group/form-parts/SelectedLectureCard.tsx
  src/components/create-study-group/form/Form.types.ts
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/create-study-group/modal/LectureSelectItem.tsx
  src/components/create-study-group/modal/LectureSelectModal.tsx
  src/constants/apiPath.ts
  src/hooks/queries/index.ts
  src/hooks/queries/queryKey.ts
  src/hooks/queries/useLectureListQuery.ts
  src/utils/form/studyGroupForm.ts
Labels: enhancement

#263 Style: 스터디 그룹 수정 스타일 반응형 수정
  src/components/common/form/DateInput.tsx
  src/components/common/form/form.styles.ts
  src/components/create-study-group/form-parts/FormFooter.tsx
  src/components/create-study-group/form-parts/LectureSelectSection.tsx
  src/components/create-study-group/form-parts/PeriodMemberSection.tsx
  src/components/create-study-group/form-parts/PrimaryInfoSection.tsx
  src/components/create-study-group/form/StudyGroupForm.tsx
  src/components/layout/layout/Layout.tsx
  src/components/study-log/StudyLogLayout.tsx
Labels: style

#267 Fix: 스케줄 생성 요청 값 id에서 uuid로 변경
  src/components/study-group-detail/modal/AddScheduleModal.tsx
Labels: bug

#272 Feature: 스케줄 수정 api 연동
  src/api/schedule.ts
  src/api/types/schedule.ts
  src/components/study-group-detail/modal/AddScheduleModal.tsx
  src/components/study-group-detail/modal/EditScheduleModal.tsx
  src/components/study-group-detail/modal/ScheduleDetailModal.tsx
  src/components/study-group-detail/modal/ScheduleForm.tsx
  src/components/study-group/StudyGroupCardOverlay.tsx
  src/components/study-group/StudyGroupMainHeader.tsx
  src/constants/apiPath.ts
  src/hooks/queries/useScheduleMutations.ts
Labels: enhancement

#279 Refactor: 스터디 그룹 수정 폼 초기 데이터
  src/components/create-study-group/form/StudyGroupFormContainer.tsx
Labels: refactor

#281 Refactor: 로그인 페이지 경로 수정
  src/lib/fetcher.ts
Labels: refactor
